spring:
  application:
    name: tasklist-backend
  config:
    import: optional:configserver:http://localhost:8888
  security:
    user:
      name: taskListService
      password: asfjsf82fdwsufhao12
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=task_project
    username: postgres
    password: Strekoza84
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: task_project
  sql:
    init:
      mode: never
      continue-on-error: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: egormalov.2007@gmail.com
    password: rcgp bktc fgwn nrfy
    properties:
      mail:
        debug : false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 9003
eureka:
  client:
    service-url:
      defaultZone=http://localhost:8761/eureka:
management:
  zipkin:
    tracing:
      endpoint:  http://localhost:9411/api/v2/spans