spring:
  application:
    name: tasklist-web
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone=http://localhost:8761/eureka:
resilience4j:
  retry:
    instances:
      default:
        enable-exponential-backoff: true