spring:
  application:
    name: tasklist-web
  config:
    import: optional:configserver::http://localhost:8888
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone=http://localhost:8761/eureka:
resilience4j:
  retry:
    instances:
      default:
        max-attempts: 5
management:
  zipkin:
    tracing:
      endpoint:  http://localhost:9411/api/v2/spans