version: '3'

volumes:
  cache:
    driver: local

services:
  api:
    build: ./TaskListService
    container_name: task_list_api
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tasklist?currentSchema=task_project
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Strekoza84
    ports:
      - '8080:8080'

  db:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Strekoza84
      - POSTGRES_DB=tasklist
    volumes:
      - ./TaskListService/src/main/resources/db-init:/docker-entrypoint-initdb.d
  web:
    container_name: task_list_web
    build: ./TaskListWeb
    ports:
      - "9090:9090"